---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Terraform Service Bucket'
Parameters:
  BucketName:
    Type: String
    Default: squids-tf-state
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: Name
          Value:
            Ref: BucketName
        - Key: Mangedby
          Value: CloudFormation
        - Key: Module
          Value: TerraformS3
        - Key: Project
          Value: Squids
      BucketName:
        Ref: BucketName

Outputs:
  S3Bucket:
    Description: 'Encrypted S3 Bucket'
    Value:
      Ref: 'S3Bucket'
