---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Terraform Service Bucket'
Parameters:
  BucketName:
    Type: String
    Default: squids-tf-state
Resources:
  # S3Key:
  #   Type: AWS::KMS::Key
  #   Properties:
  #     KeyPolicy:
  #       Version: 2012-10-17
  #       Id: key-s3
  #       Statement:
  #         - Sid:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Mangedby
          Value: CloudFormation
        - Key: Module
          Value: TerraformS3
        - Key: Project
          Value: Squids
      BucketName: !Ref BucketName
